import { Metadata } from "next";

// import Contact from "./Contact";

export const metadata: Metadata = {
  title: "Contact us",
  description: "Generated by create next app",
};

export default function ContactUs() {
  return (
    <div className="w-full h-auto bg-black pt-52">
      {/* <Card>
        {/* <Contact /> */}
      {/* </Card> */}
      Contacts page
    </div>
  );
}
