import { Metadata } from "next";
import MoviesPage from "./MoviesPage";

export interface search {
  searchParams: Promise<{
    limit: string;
    page: string;
  }>;

}

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg",
  },
};

export default function page({ searchParams }: search) {
  return (
    <>
      <MoviesPage searchParams={searchParams} />
    </>
  );
}
