import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Events",
  description: "Generated by create next app",
  icons: {
    icon: "/next.svg",
  },
};

export default function layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
